version: "3.8"

services:
    pymongo:
        #        image: python:alpine
        build: ./python_mongo
        #        command: sh -c "pip install --no-cache-dir pymongo && python3 /home/main.py"
        entrypoint: python3 /home/main.py
        volumes:
          - ./python_mongo:/home
        profiles:
            - python_only_run
        networks:
            graph_net:

    mongo:
        image: mongo
        volumes:
            - ./mongo/db:/data/db
            - ./mongo/input_docs-archives:/home/input_docs-archives
        ports:
            - 8089:27017
        networks:
            graph_net:

    graphdb:
        build: spring-db/grafo
        entrypoint: java -jar /app.jar --server.port=8080
        ports:
            - 8090:8080
        networks:
            graph_net:
        depends_on:
            - mongo

    graphmanager:
        build: spring-func-manager/grafo-func-manager
        entrypoint: java -jar /app.jar --server.port=8081
        ports:
            - 8091:8081
        networks:
            graph_net:
        depends_on:
            - graphdb

    angular:
        image: nginx:alpine
        volumes:
            - ./ang/grafo1/dist/grafo1:/usr/share/nginx/html
            - ./ang/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 81:80
        networks:
             graph_net:
        depends_on:
            - graphmanager

    prom:
        image: prom/prometheus
        ports:
            - 8092:9090
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
             graph_net:

    grafana:
        image: grafana/grafana-oss
        ports:
            - 8093:3000
        volumes:
            - ./grafana/data:/var/lib/grafana
        networks:
             graph_net:

networks:
    graph_net:
