version: "3.8"

services:
    mongo:
        image: mongo
        volumes:
            - ./mongo/db:/data/db
            - ./mongo/input_docs-archives:/home/input_docs-archives
        ports:
            - 8089:27017
        networks:
            graph_net:

    graphdb:
        build: spring-db/grafo
        entrypoint: java -jar /app.jar --server.port=8080
        ports:
            - 8090:8080
        networks:
            graph_net:
        depends_on:
            - mongo

#    graphmanager:
#        build: spring-func-manager/grafo-func-manager
#        entrypoint: java -jar /app.jar --server.port=8081
#        ports:
#            - 8091:8081
#        networks:
#            graph_net:
#        depends_on:
#            - graphdb

#    angular:
#        image: nginx:alpine
#        volumes:
#            - ./ang/grafo1/dist/grafo1:/usr/share/nginx/html
#            - ./ang/nginx.conf:/etc/nginx/conf.d/default.conf
#        ports:
#            - 80:80
#        networks:
#             graph_net:
#        depends_on:
#            - graphmanager

networks:
    graph_net:
